spring.application.name=EstacaoMetereologica

# URL de conexão (JDBC)
spring.datasource.url=jdbc:postgresql://db.eyuggwjixeuraiqjbnze.supabase.co:5432/postgres
# Credenciais
spring.datasource.username=postgres
spring.datasource.password=EstacaoMetereologica123

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect